### ISSUE TITLE
Terraqueous tree chop client crash

### ISSUE THREAD

**Issue by MachinegunMarty** [DuchLord/TreeChopper#21]
Hi Duchlord,

Added all the tree's from all the mods i'm using in the config file with /tch printname 1 . 

Works great !

Except for terraqueous trees.... they crash my client, not my server.

to test add "tile.terraqueous.trunk" to your config. This covers all the trees terraqueous has.

Anything from apple to peach trees gives me this error:

java.lang.IllegalArgumentException: Cannot get property null as it does not exist in BlockStateContainer{block=terraqueous:trunk1, properties=[axis, treevariant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at treechopper.common.handler.TreeHandler.logAnalyze(TreeHandler.java:129)
	at treechopper.common.handler.TreeHandler.treeAnalyze(TreeHandler.java:85)
	at treechopper.proxy.ClientProxy.interactTree(ClientProxy.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1342_CommonProxy_interactTree_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1010)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:229)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1459)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at treechopper.common.handler.TreeHandler.logAnalyze(TreeHandler.java:129)
	at treechopper.common.handler.TreeHandler.treeAnalyze(TreeHandler.java:85)
	at treechopper.proxy.ClientProxy.interactTree(ClientProxy.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1342_CommonProxy_interactTree_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1010)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:229)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1459)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

Hope it helps you to make this mod even better.

grtz,

Machinegun Marty

**Comment by MachinegunMarty** [comment]
Any ETA when you aree gonna release this update ?

**Comment by DuchLord** [comment]
Within a few hours..

**Comment by MachinegunMarty** [comment]
Awesome ! 

Thanx for the info !
